# Generated by Django 5.2.12 on 2026-03-26 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AirportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], max_length=1)),
                ('distance_km', models.PositiveIntegerField(help_text='Distance in kilometers')),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_routes', to='app.airport')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_routes', to='app.airport')),
            ],
            options={
                'indexes': [models.Index(fields=['position'], name='app_airport_positio_0411bb_idx'), models.Index(fields=['duration'], name='app_airport_duratio_eb77b5_idx'), models.Index(fields=['distance_km'], name='app_airport_distanc_6b2591_idx')],
                'unique_together': {('source', 'position')},
            },
        ),
    ]
