# Generated by Django 5.2.12 on 2026-03-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='airportroute',
            name='app_airport_duratio_eb77b5_idx',
        ),
        migrations.AlterField(
            model_name='airportroute',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
    ]
